# config/database.yml
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "root") %>
  password:
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", "3306") %>

development:
  <<: *default
  database: soccer_stats_development

test:
  <<: *default
  database: soccer_stats_test

production:
  <<: *default
  database: soccer_stats_production